/* Create SparcElectricHybridDW */

USE [master]
GO
/****** Object:  Database [SparcElectricHybridDW]    Script Date: 7/30/2022 5:14:29 PM ******/
CREATE DATABASE [SparcElectricHybridDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SparcElectricHybridDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SparcElectricHybridDW.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SparcElectricHybridDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SparcElectricHybridDW_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SparcElectricHybridDW] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SparcElectricHybridDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SparcElectricHybridDW] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET ARITHABORT OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SparcElectricHybridDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SparcElectricHybridDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SparcElectricHybridDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SparcElectricHybridDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET RECOVERY FULL 
GO
ALTER DATABASE [SparcElectricHybridDW] SET  MULTI_USER 
GO
ALTER DATABASE [SparcElectricHybridDW] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SparcElectricHybridDW] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SparcElectricHybridDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SparcElectricHybridDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SparcElectricHybridDW] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SparcElectricHybridDW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SparcElectricHybridDW', N'ON'
GO
ALTER DATABASE [SparcElectricHybridDW] SET QUERY_STORE = OFF
GO