theme: jekyll-theme-cayman
title: SparcElectric Mixed-Use Data Warehouse Test-bed
description: Builds test-bed data, supplies ETL and visualizations, for an imaginary power company named SparcElectric.
